# Файл: hosts.tftpl

[webservers]
web-1 ansible_host=89.169.145.64 fqdn=web-1.ru-central1.internal
web-2 ansible_host=84.252.130.3 fqdn=web-2.ru-central1.internal

[databases]
main ansible_host=111.88.252.234 fqdn=main.ru-central1.internal
replica ansible_host=89.169.159.28 fqdn=replica.ru-central1.internal

[storage]
storage ansible_host=10.0.1.30 fqdn=storage.ru-central1.internal
